version: '3.4'

services:
    php:
        build:
            context: .
            target: php
        depends_on:
            - db
        env_file:
            - ./.env
        volumes:
            - .:/srv/app:rw,cached
        ports:
            - 9000

    api:
        build:
            context: .
            target: nginx
        depends_on:
            - php
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./public:/srv/app/public:ro

    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - ${DB_PORT}:5432
